### ISSUE TITLE
运行中张量尺寸问题

### ISSUE THREAD

**Issue by leehr1227** [gengshan-y/high-res-stereo#14]
你好，打扰了。
我尝试运行了你的代码，发现在models/submodule.py中的decoderBlock类中使用了3d池化，第一次池化时，pool_size取值为1，导致池化核的尺寸就是输入的后三个维度，池化的结果让后三个维度长度全部变成1，致使接下来的程序无法运行。请问有好的解决办法嘛，还是我使用的方式不对？

**Comment by gengshan-y** [comment]
What's the error message and the value of d, h, w?

**Comment by leehr1227** [comment]
d=3，h=4，w=8。
由于池化后的结果尺寸为（1，32，1，1，1），卷积运算无法处理这样的张量。

**Comment by gengshan-y** [comment]
Interesting, it works fine for me: 

Input tensor shape:[1, 32, 1, 1, 1]
operation: Conv3d(32, 32, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
output shape: [1, 32, 1, 1, 1]

I'm guessing it's a pytorch version issue. Let me know the exact error message and your pytorch version so that I can take a further look.

**Comment by leehr1227** [comment]
我在ubuntu18.04尝试过python3.7，pytorch1.0.0，仍然不成功。

**Comment by gengshan-y** [comment]
What's the error message?

**Comment by leehr1227** [comment]
对不起，这个问题我需要在第二天才能答复你。

**Comment by gengshan-y** [comment]
Sure

**Comment by leehr1227** [comment]
这里是运行情况：

leehr@leehr-OptiPlex-9020:~/code/HSMNet$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.0.0'
>>> 
leehr@leehr-OptiPlex-9020:~/code/HSMNet$ python3 train.py
Number of model parameters: 3174132
WARNING:tensorflow:From /home/leehr/code/HSMNet/utils/logger.py:33: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

0.001
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    main()
  File "train.py", line 154, in main
    loss,vis = train(imgL_crop,imgR_crop, disp_crop_L)
  File "train.py", line 113, in train
    stacked,entropy = model(imgL,imgR)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leehr/code/HSMNet/models/hsm.py", line 70, in forward
    feat6_2x, cost6 = self.decoder6(feat6)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leehr/code/HSMNet/models/submodule.py", line 136, in forward
    out = self.pool_convs[i](out)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1619, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 32, 1, 1, 1])

**Comment by leehr1227** [comment]
补充一句，问题应该来自于之后的BatchNorm3d，而不是Conv3d。

**Comment by gengshan-y** [comment]
The problem is caused by [batchnorm set to training mode](https://discuss.pytorch.org/t/error-expected-more-than-1-value-per-channel-when-training/26274/2).

Are you training the model? If so, the batch dimension should be greater than one.

**Comment by leehr1227** [comment]
原来如此，非常感谢。
