### ISSUE TITLE
Dimension error during traing

### ISSUE THREAD

**Issue by Hahaemmm** [gengshan-y/high-res-stereo#28]
When I tried to train on the sceneflow data set, I encountered this problem, but I did not have this problem in previous training. How should I solve it?

`
Number of model parameters: 3174132
5909 batches per epoch
0.001
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Epoch 1 Iter 0 training loss = 124.344 , time = 13.91
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    main()
  File "train.py", line 156, in main
    for batch_idx, (imgL_crop, imgR_crop, disp_crop_L) in enumerate(TrainImgLoader):
  File "/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/caixianchen/anaconda3/envs/hrs/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 218, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 512 and 509 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1333`

**Comment by Hahaemmm** [comment]
In file MiddleburyLoader.py 
I add code at line 78
`if left_img.shape[0] != dataL.shape[0]:
            print('EEEEEEEEEEEEEEEEEEEEE')
            print ('L ' + str(left_img.shape))
            print ('R ' + str(right_img.shape))
            print ('D ' + str(dataL.shape))`

got the error message :
`L (544, 960, 3)
R (544, 960, 3)
D (540, 960)`
 
I don't understand why the size of the picture is wrong
